{{ if eq .Values.tools.enabled true }}
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: {{ .Values.tools.namespace }}
  labels:
    app: keycloak
spec:
  selector:
    app: keycloak
  ports:
    - name: http
      port: 8080
      protocol: TCP
{{- if eq .Values.authorino.enabled false }}
  type: LoadBalancer
{{- end }}
{{end}}
