{{- if .Values.authorino.enabled }}
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: keycloak
  namespace: {{ .Values.tools.namespace }}
  labels:
    app: keycloak
spec:
  to:
    kind: Service
    name: keycloak
  port:
    targetPort: http
{{- end }}