{{- if and (eq .Values.tools.enabled true) (eq .Values.authorino.enabled false) }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-issuer
spec:
  selfSigned: {}
{{- end }}