{{if and (eq .Values.istio.istioProvider "ossm") (eq .Values.authorino.enabled false) }}
apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: istio-system-operator
spec: {}
{{end}}
