kuadrant:
  # non-existing namespace to which kuadrant operator will be installed and Kuadrant CR created :(
  # ; if existing openshift-operators namespace is used no additional OperatorGroup will be created
  namespace: kuadrant-system
  # OLM index image to use for kuadrant deployment (creates catalogsource in openshift-marketplace namespace)
  # ; if left empty it uses official released redhat-operators catalogsource in openshift-marketplace namespace
  indexImage: 'quay.io/kuadrant/kuadrant-operator-catalog:v0.11.0'
  operatorName: kuadrant-operator  # rhcl-operator if installing downstream
  channel: stable  # can be either 'preview' for nightly builds or 'stable' for release builds

authorino:
  enabled: true
  operatorName: authorino-operator 
  channel: tech-preview-v1
  namespace: openshift-operators
  indexImage: 'registry-proxy.engineering.redhat.com/rh-osbs/iib:885534'

gatewayAPI:
  version: v1.1.0  # v1.0.0, v1.1.0 available

istio:
  namespace: istio-system
  operatorNamespace: istio-system-operator
  istioProvider: ossm3  # need to be set to 'ossm3'
  ossm3: # Openshift Service Mesh, but version 3
    version: v1.23.0
    operator:
      channel: candidates
      startingCSV: servicemeshoperator3.v3.0.0-tp.1
      installPlanApproval: Automatic  # if set to Manual InstallPlan has to be approved manually

certManager:
  operator:
    channel: stable-v1
    startingCSV: cert-manager-operator.v1.14.0
    installPlanApproval: Automatic  # if set to Manual InstallPlan has to be approved manually

tools:
  enabled: false  # if 'true' the testing environment is set up as well
  namespace: tools
  jaeger:
    image: quay.io/jaegertracing/all-in-one
  mockserver:
    image: quay.io/mganisin/mockserver:latest
  keycloak:
    operator:
      channel: stable-v26
      startingCSV: rhbk-operator.v26.0.5-opr.1
      installPlanApproval: Automatic  # if set to Manual InstallPlan has to be approved manually
    database:
      image: registry.redhat.io/rhel9/postgresql-16:latest

additionalManifests: []
