{{- if and (eq .Values.istio.istioProvider "sail") (eq .Values.authorino.enabled false) }}
apiVersion: operator.istio.io/v1alpha1
kind: Istio
metadata:
  name: default
spec:
  namespace: {{ .Values.istio.namespace }}
  values:
    global:
      hub: gcr.io/istio-release
      proxy:
        logLevel: info
    pilot:
      autoscaleMin: 2
  version: {{ .Values.istio.sail.version }}
{{- end }}
