{{ if and (ne .Values.kuadrant.namespace "openshift-operators") (eq .Values.authorino.enabled false) }}
apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: {{ .Values.kuadrant.namespace }}
spec: {}
{{ end }}
