{{- if and .Values.kuadrant.indexImage (eq .Values.authorino.enabled false) }}
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: kuadrant-upstream
  namespace: {{ .Values.kuadrant.namespace }}
spec:
  image: {{ .Values.kuadrant.indexImage }}
  sourceType: grpc
{{- end }}
