{{- if and (ne .Values.kuadrant.namespace "openshift-operators") (eq .Values.authorino.enabled false)  }}
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: kuadrant-system
  namespace: {{ .Values.kuadrant.namespace }}
spec:
  upgradeStrategy: Default
{{- end }}
