{{if and (eq .Values.istio.istioProvider "ossm3") (eq .Values.authorino.enabled false) }}
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: istio-system-operator
  namespace: {{ .Values.istio.operatorNamespace }}
spec:
  upgradeStrategy: Default
{{end}}
