{{- if and (eq .Values.istio.istioProvider "ossm") (eq .Values.authorino.enabled false) }}
apiVersion: maistra.io/v2
kind: ServiceMeshControlPlane
metadata:
  name: istiocontrolplane
  namespace: {{ .Values.istio.namespace }}
spec:
  security:
    manageNetworkPolicy: false
  version: {{ .Values.istio.ossm.version }}
  mode: ClusterWide
  policy:
    type: Istiod
  profiles:
    - default
  telemetry:
    type: Istiod
  addons:
    prometheus:
      enabled: false
    kiali:
      enabled: false
    grafana:
      enabled: false
  runtime:
    components:
      pilot:
        deployment:
          replicas: 2
{{- end }}